sonar.projectKey=REEMPLAZAR_ORG_lavanderia
sonar.organization=REEMPLAZAR_ORG
sonar.sources=src,public
sonar.tests=test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,coverage/**,docs/**
