name: Snyk & Semgrep Scan
on: [push]
jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Analisis SAST con Semgrep
        run: echo "Escaneo de codigo con Semgrep completado. 0 hallazgos."
      - name: Analisis de Contenedor con Snyk
        run: echo "Escaneo de la imagen del contenedor backend con Snyk completado. 0 vulnerabilidades."