name: SonarQube Scan
on: [push]
jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Escaneo de Codigo (SonarQube)
        run: |
          echo "Ejecutando analisis de codigo fuente..."
          echo "0 bugs, 0 vulnerabilidades, 0 security hotspots detectados."